-- Session Paths to Purchase section reuses analytics_purchase_paths with
-- p_steps=10, p_top_n=10 (called from the API route directly).
-- The within-session RPC below was attempted but abandoned because
-- order_placed session_ids are server-side only with no co-located browser events.
-- No DB changes needed beyond what 0024 already provides.
